
package com.meihuichina.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * http://180.166.5.194:11080	外网正式环境
 * http://180.166.5.194:18880  外网测试环境
 * http://192.168.123.75:8088  本地测试环境
 * http://192.168.123.162:8088 测试环境
 */
@WebServiceClient(name = "PublishInformationCenterDataService", targetNamespace = "http://webservice.meihuichina.com", wsdlLocation = "http://180.166.5.194:11080/WebServiceServer/services/PublishInformationCenterData?wsdl")
public class PublishInformationCenterDataService
    extends Service
{

    private final static URL PUBLISHINFORMATIONCENTERDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLISHINFORMATIONCENTERDATASERVICE_EXCEPTION;
    private final static QName PUBLISHINFORMATIONCENTERDATASERVICE_QNAME = new QName("http://webservice.meihuichina.com", "PublishInformationCenterDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://180.166.5.194:11080/WebServiceServer/services/PublishInformationCenterData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLISHINFORMATIONCENTERDATASERVICE_WSDL_LOCATION = url;
        PUBLISHINFORMATIONCENTERDATASERVICE_EXCEPTION = e;
    }

    public PublishInformationCenterDataService() {
        super(__getWsdlLocation(), PUBLISHINFORMATIONCENTERDATASERVICE_QNAME);
    }

    public PublishInformationCenterDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLISHINFORMATIONCENTERDATASERVICE_QNAME, features);
    }

    public PublishInformationCenterDataService(URL wsdlLocation) {
        super(wsdlLocation, PUBLISHINFORMATIONCENTERDATASERVICE_QNAME);
    }

    public PublishInformationCenterDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLISHINFORMATIONCENTERDATASERVICE_QNAME, features);
    }

    public PublishInformationCenterDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublishInformationCenterDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublishInformationCenterData
     */
    @WebEndpoint(name = "PublishInformationCenterData")
    public PublishInformationCenterData getPublishInformationCenterData() {
        return super.getPort(new QName("http://webservice.meihuichina.com", "PublishInformationCenterData"), PublishInformationCenterData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishInformationCenterData
     */
    @WebEndpoint(name = "PublishInformationCenterData")
    public PublishInformationCenterData getPublishInformationCenterData(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.meihuichina.com", "PublishInformationCenterData"), PublishInformationCenterData.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLISHINFORMATIONCENTERDATASERVICE_EXCEPTION!= null) {
            throw PUBLISHINFORMATIONCENTERDATASERVICE_EXCEPTION;
        }
        return PUBLISHINFORMATIONCENTERDATASERVICE_WSDL_LOCATION;
    }

}
