
package com.meihuichina.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublishInformationCenterData", targetNamespace = "http://webservice.meihuichina.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublishInformationCenterData {


    /**
     * 
     * @param sig
     * @param account
     * @param ts
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getImgUrlByAccountReturn", targetNamespace = "http://webservice.meihuichina.com")
    @RequestWrapper(localName = "getImgUrlByAccount", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetImgUrlByAccount")
    @ResponseWrapper(localName = "getImgUrlByAccountResponse", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetImgUrlByAccountResponse")
    public String getImgUrlByAccount(
        @WebParam(name = "account", targetNamespace = "http://webservice.meihuichina.com")
        String account,
        @WebParam(name = "ts", targetNamespace = "http://webservice.meihuichina.com")
        long ts,
        @WebParam(name = "sig", targetNamespace = "http://webservice.meihuichina.com")
        String sig);

    /**
     * 
     * @param sig
     * @param dataName
     * @param account
     * @param ts
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getTrafficDataByDataNameReturn", targetNamespace = "http://webservice.meihuichina.com")
    @RequestWrapper(localName = "getTrafficDataByDataName", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetTrafficDataByDataName")
    @ResponseWrapper(localName = "getTrafficDataByDataNameResponse", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetTrafficDataByDataNameResponse")
    public String getTrafficDataByDataName(
        @WebParam(name = "account", targetNamespace = "http://webservice.meihuichina.com")
        String account,
        @WebParam(name = "ts", targetNamespace = "http://webservice.meihuichina.com")
        long ts,
        @WebParam(name = "sig", targetNamespace = "http://webservice.meihuichina.com")
        String sig,
        @WebParam(name = "dataName", targetNamespace = "http://webservice.meihuichina.com")
        String dataName);

    /**
     * 
     * @param sig
     * @param dataName
     * @param account
     * @param ts
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getDataCountByDataNameReturn", targetNamespace = "http://webservice.meihuichina.com")
    @RequestWrapper(localName = "getDataCountByDataName", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetDataCountByDataName")
    @ResponseWrapper(localName = "getDataCountByDataNameResponse", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetDataCountByDataNameResponse")
    public String getDataCountByDataName(
        @WebParam(name = "account", targetNamespace = "http://webservice.meihuichina.com")
        String account,
        @WebParam(name = "ts", targetNamespace = "http://webservice.meihuichina.com")
        long ts,
        @WebParam(name = "sig", targetNamespace = "http://webservice.meihuichina.com")
        String sig,
        @WebParam(name = "dataName", targetNamespace = "http://webservice.meihuichina.com")
        String dataName);

    /**
     * 
     * @param sig
     * @param dataName
     * @param currentPage
     * @param account
     * @param ts
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getTrafficDataByDataNameAndPageReturn", targetNamespace = "http://webservice.meihuichina.com")
    @RequestWrapper(localName = "getTrafficDataByDataNameAndPage", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetTrafficDataByDataNameAndPage")
    @ResponseWrapper(localName = "getTrafficDataByDataNameAndPageResponse", targetNamespace = "http://webservice.meihuichina.com", className = "com.meihuichina.webservice.GetTrafficDataByDataNameAndPageResponse")
    public String getTrafficDataByDataNameAndPage(
        @WebParam(name = "account", targetNamespace = "http://webservice.meihuichina.com")
        String account,
        @WebParam(name = "ts", targetNamespace = "http://webservice.meihuichina.com")
        long ts,
        @WebParam(name = "sig", targetNamespace = "http://webservice.meihuichina.com")
        String sig,
        @WebParam(name = "dataName", targetNamespace = "http://webservice.meihuichina.com")
        String dataName,
        @WebParam(name = "currentPage", targetNamespace = "http://webservice.meihuichina.com")
        int currentPage);

}
